export default {
  logo: require('../assets/logo.png'),
  mat: require('../assets/view.png'),
  matdong: require('../assets/hidden.png'),
  google: require('../assets/icons8-google-64.png'),
  home: require('../assets/icons8-google-home-64.png'),
  giohang: require('../assets/icons8-fast-cart-64.png'),
  love: require('../assets/icons8-love-letter-64.png'),
  chuong: require('../assets/icons8-bell-64.png'),
  menu: require('../assets/icons8-menu-64.png'),
  profile: require('../assets/icons8-user-default-64.png'),
  timkiem: require('../assets/icons8-search-64.png'),
  giohang2: require('../assets/icons8-cart-64.png'),
  tim: require('../assets/icons8-heart-50.png'),
  comment: require('../assets/icons8-comment-32.png'),
  star: require('../assets/icons8-star-50.png'),
  back: require('../assets/icons8-back-50.png'),
  diachi: require('../assets/icons8-placeholder-62.png'),
  tim2: require('../assets/icons8-heart-48.png'),
  huychuong: require('../assets/icons8-medal-48.png'),
  time: require('../assets/icons8-time-48.png'),
  qua: require('../assets/icons8-gift-50.png'),
  bag_tui: require('../assets/icons8-bag-64.png'),
  comment2: require('../assets/icons8-comment-100.png'),
  map: require('../assets/map.jpg'),
  next: require('../assets/icons8-next-50.png'),
  dong: require('../assets/icons8-x-50.png'),
};
